export type StudioControlEntry = {
  id: string;
  title: string;
  group: "Foundation" | "Colour" | "Typography" | "Sizing" | "Style" | "Media" | "Inspector";
  purpose: string;
  owner: string;
  consumers: string[];
  dependencies?: { kind: "inherits" | "uses"; label: string; entryId?: string; detail: string }[];
  states: string;
  compatibility: string;
};

export const studioControlEntries: StudioControlEntry[] = [
  { id: "slider-foundation", title: "Slider", group: "Foundation", purpose: "Set and preview the shared accent and hover colours inherited by Studio range controls.", owner: "ACM Studio shared range styling", consumers: ["Background image width in Studio inspectors", "Design canvas zoom, opacity, edge cleanup and arrowhead size", "Range specimens in the Ribbon catalogue"], dependencies: [{ kind: "uses", label: "Gutenberg accent token", detail: "--studio-range-accent defaults to var(--gutenberg-accent); --studio-range-hover-accent falls back to the accent. The Controls preview can temporarily override either colour." }], states: "Shared accent and hover colours, keyboard focus and disabled state; temporary colour previews and reset.", compatibility: "Consumers keep their existing native range values, bounds, steps and behaviour. Gradient hue and alpha controls retain their specialist colour tracks." },
  { id: "colour-picker", title: "Colour picker", group: "Colour", purpose: "Choose a preset or custom colour, including independent Default and Hover values.", owner: "ACM Studio controls", consumers: ["Paragraph text and links", "Separator colour", "Block backgrounds"], dependencies: [{ kind: "uses", label: "@acm/styles palette", detail: "Palette roles and swatch values come from UNIVERSAL_STYLE_PRESET.palette." }], states: "Unset and explicit colours, selected swatches, focus, contrast warning, Default/Hover, clear and disabled.", compatibility: "Uses the shared ACM palette and preserves explicit custom colour values." },
  { id: "background-selection", title: "Background colour and gradient", group: "Colour", purpose: "Choose a solid palette colour or edit a linear or radial gradient.", owner: "ACM Studio controls", consumers: ["Paragraph", "Quote", "Group"], dependencies: [{ kind: "uses", label: "Colour picker", entryId: "colour-picker", detail: "Selects the solid background colour." }, { kind: "uses", label: "Gradient picker", detail: "Edits gradient type, stops, opacity and angle; its hue and alpha tracks use specialist styling." }, { kind: "uses", label: "@acm/styles palette.textPrimary", detail: "Supplies the default text colour when contrast assessment is enabled." }], states: "Stacked colour and gradient controls, twelve default presets, colour stops, opacity, type, angle and reset.", compatibility: "Preserves legacy gradient names and stores validated custom gradient stops in ParagraphStyle." },
  { id: "custom-font-size", title: "Custom font size", group: "Typography", purpose: "Edit supported custom font-size units with a compact range control.", owner: "ACM Studio controls", consumers: ["Paragraph and shared Typography inspectors"], dependencies: [{ kind: "inherits", label: "Slider foundation", entryId: "slider-foundation", detail: "The range thumb and keyboard focus ring use --studio-range-accent; pointer hover uses --studio-range-hover-accent, which falls back to the accent." }], states: "px, em, rem, vw and vh; numeric entry, unit menu, range adjustment, pointer drag and reset.", compatibility: "Normalises values through the existing custom font-size contract." },
  { id: "font-size-appearance", title: "Font size and Appearance", group: "Typography", purpose: "Switch between named font-size presets and custom sizing, then choose a font weight or italic appearance.", owner: "ACM Studio controls", consumers: ["Paragraph and shared Typography inspectors"], dependencies: [{ kind: "uses", label: "Custom font size", entryId: "custom-font-size", detail: "Shown when Custom mode is selected." }, { kind: "inherits", label: "Slider foundation", entryId: "slider-foundation", detail: "In Custom mode, its embedded range inherits the shared accent, hover colour and focus ring via Custom font size." }], states: "Preset and custom modes, size selection, default Appearance, regular through black weights and italic variants.", compatibility: "Stores the existing fontSize, fontSizeCustom and appearance fields without changing their values." },
  { id: "line-height", title: "Line height", group: "Typography", purpose: "Set or clear the line height of a text block or selected List Item.", owner: "ACM Studio controls", consumers: ["Shared Typography inspectors", "Selected List Item"], states: "Default or explicit value, decimal keyboard input and existing CSS line-height units.", compatibility: "Stores the existing lineHeight field without changing its value format." },
  { id: "paragraph-length", title: "Paragraph length", group: "Sizing", purpose: "Set a scalar length for paragraph-specific spacing and indentation.", owner: "ACM Studio controls", consumers: ["Paragraph line indent", "Shared legacy inspector settings"], dependencies: [{ kind: "inherits", label: "Slider foundation", entryId: "slider-foundation", detail: "The range thumb and keyboard focus ring use --studio-range-accent; pointer hover uses --studio-range-hover-accent, which falls back to the accent." }], states: "Empty/default, positive and negative values, supported units, range and reset.", compatibility: "Keeps supported CSS length units and preserves the block style value." },
  { id: "box-length", title: "Box dimensions", group: "Sizing", purpose: "Edit linked or separate sides, axes and corners.", owner: "ACM Studio controls", consumers: ["Padding", "Margin", "Border width", "Border radius"], dependencies: [{ kind: "inherits", label: "Slider foundation", entryId: "slider-foundation", detail: "The range thumb and keyboard focus ring use --studio-range-accent; pointer hover uses --studio-range-hover-accent, which falls back to the accent." }], states: "Linked and split values, units, custom number entry, keyboard focus and reset.", compatibility: "Expands and serialises the existing CSS shorthand length fields." },
  { id: "preset-number", title: "Preset number", group: "Sizing", purpose: "Choose a common pixel value, keep the current custom number, or return to Default.", owner: "ACM Studio controls", consumers: ["Columns gaps and padding", "Grid minimum column width"], states: "Default, every configured preset, custom value, bounds and reset.", compatibility: "Stores pixel numbers in the existing numeric layout fields." },
  { id: "image-dimensions", title: "Image dimensions", group: "Media", purpose: "Set image aspect ratio, explicit dimensions and fit behaviour.", owner: "ACM Studio controls", consumers: ["Image", "Cover"], states: "Original and named aspect ratios, automatic and explicit width/height, conditional Cover/Contain scale.", compatibility: "Conditional scale remains available only when a non-original aspect ratio is selected." },
  { id: "focal-position", title: "Focal position", group: "Media", purpose: "Set the horizontal and vertical position used when an image is cropped.", owner: "ACM Studio controls", consumers: ["Image", "Cover", "Background images"], dependencies: [{ kind: "inherits", label: "Slider foundation", entryId: "slider-foundation", detail: "The range thumb and keyboard focus ring use --studio-range-accent; pointer hover uses --studio-range-hover-accent, which falls back to the accent." }], states: "Separate horizontal and vertical values, numeric and range presentations, 0–100 bounds.", compatibility: "Image focal controls are available only when a crop ratio is selected; backgrounds retain their range inputs." },
  { id: "border-settings", title: "Border settings", group: "Style", purpose: "Set border colour, style, width, radius and optional shadow as one grouped capability.", owner: "ACM Studio controls", consumers: ["Styled blocks", "Image", "Cover"], dependencies: [{ kind: "uses", label: "Box dimensions", entryId: "box-length", detail: "Sets border width and radius." }, { kind: "uses", label: "Border colour control", detail: "Selects the border colour." }, { kind: "inherits", label: "Slider foundation", entryId: "slider-foundation", detail: "The embedded Box dimensions range controls inherit the shared thumb accent, focus ring and pointer hover colour." }], states: "Default and explicit colour, none/solid/dashed/dotted style, linked or split measurements, radius, shadow and reset.", compatibility: "Writes the current ParagraphStyle fields; legacy colour values remain editable through the colour field." },
  { id: "inspector-tools", title: "Inspector options and reset", group: "Inspector", purpose: "Show or hide optional controls in Gutenberg and Studio groups and reset a section.", owner: "ACM Studio inspector", consumers: ["Blocks with shared style inspectors"], states: "Optional controls, source grouping, menu dismissal, section reset and unavailable reset.", compatibility: "Option availability is generated from each block capability profile." },
  { id: "inspector-accordion", title: "Accordion section", group: "Inspector", purpose: "Group related inspector settings behind a collapsible section heading.", owner: "ACM Studio inspector", consumers: ["Block, template and document inspector sections"], states: "Expanded and collapsed; semantic disclosure control and contained settings.", compatibility: "The catalogue uses the shared production accordion component." },
];

export const studioControlGroups = ["Foundation", "Colour", "Typography", "Sizing", "Style", "Media", "Inspector"] as const;
export function controlGroupId(group: string) {
  return `control-group-${group.toLocaleLowerCase("en-GB")}`;
}
export const studioControlEntryById = Object.fromEntries(studioControlEntries.map(entry => [entry.id, entry])) as Record<string, StudioControlEntry | undefined>;
