import type { StudioDocument } from "./editor-model";
import type { TemplateStore, TemplateAssignment, TemplateDefaults } from "./template-model";

export function DocumentTemplateControls({ document, store, writable, error, onChange, onDefaultsChange }: { document: StudioDocument; store: TemplateStore; writable: boolean; error: string | null; onChange: (assignment?: TemplateAssignment) => void; onDefaultsChange?: (defaults: TemplateDefaults) => void }) {
  const assignment = store.assignments.find(item => item.documentId === document.id);
  const set = assignment ? store.sets.find(item => item.id === assignment.setId) : undefined;
  const template = assignment ? set?.templates.find(item => item.id === assignment.templateId) : undefined;
  const defaults = template?.defaults ?? set?.defaults ?? {};
  return <section className="inspector-section template-assignment"><h3>Template</h3><label>Assignment<select aria-label="Site Template" disabled={!writable} value={assignment ? `${assignment.setId}/${assignment.templateId}` : ""} onChange={event => {
    if (!event.target.value) { onChange(); return; }
    const [setId, templateId] = event.target.value.split("/"); onChange({ documentId: document.id, kind: document.kind, setId, templateId });
  }}><option value="">Existing Presentation</option>{store.sets.map(item => <optgroup key={item.id} label={item.name}>{item.templates.filter(template => template.kind === document.kind).map(template => <option key={template.id} value={`${item.id}/${template.id}`}>{template.name}</option>)}</optgroup>)}</select></label>{assignment ? <><p className="setting-note">Values below are supplied by {set?.name ?? "the selected template"} unless the document overrides them.</p><label>Template author<input disabled={!writable} value={defaults.author ?? ""} onChange={event => onDefaultsChange?.({ ...defaults, author: event.target.value })} placeholder="No default author" /></label>{document.kind === "post" ? <><label>Template category<select disabled={!writable} value={defaults.category ?? ""} onChange={event => onDefaultsChange?.({ ...defaults, category: (event.target.value || undefined) as TemplateDefaults["category"] })}><option value="">No default category</option><option>Technology</option><option>Excel</option><option>Personal</option></select></label><label>Template tags<input disabled={!writable} value={(defaults.tags ?? []).join(", ")} onChange={event => onDefaultsChange?.({ ...defaults, tags: event.target.value.split(",").map(tag => tag.trim()).filter(Boolean) })} placeholder="No default tags" /></label></> : null}</> : null}{error ? <p role="alert">{error}</p> : null}{assignment ? <a href={`/studio/templates?set=${encodeURIComponent(assignment.setId)}&target=${encodeURIComponent(assignment.templateId)}`}>Edit Template</a> : <a href="/studio/templates">Manage Templates</a>}</section>;
}
