"use client";
import { useState } from "react";
import type { ContentBlock } from "../content/model";
import { BlockInspector } from "./studio-inspectors";
import { InspectorAccordionSection, InspectorContentDisabledProvider } from "./inspector-accordion";
import { templateId, templateElementLabel, type TemplateSet, type PageTemplate, type TemplatePart, type SiteLink, type SiteStyles } from "./template-model";

export function TemplateTextSetting({ label, value, onCommit, placeholder }: { label: string; value: string; onCommit: (value: string) => void; placeholder?: string }) {
  return <label>{label}<input key={value} defaultValue={value} placeholder={placeholder} onBlur={event => { if (event.target.value !== value) onCommit(event.target.value); }} onKeyDown={event => { if (event.key === "Enter") event.currentTarget.blur(); }} /></label>;
}

function LinkSettings({ title, links, onChange, disabled = false }: { title: string; links: SiteLink[]; onChange: (links: SiteLink[]) => void; disabled?: boolean }) {
  const [label, setLabel] = useState(""); const [url, setUrl] = useState("");
  return <InspectorAccordionSection title={title} contentDisabled={disabled}>{links.map((link, index) => <div key={link.id} className="template-link-item">
    <TemplateTextSetting label="Link Label" value={link.label} onCommit={label => onChange(links.map(item => item.id === link.id ? { ...item, label } : item))} />
    <TemplateTextSetting label="Destination" value={link.url} onCommit={url => onChange(links.map(item => item.id === link.id ? { ...item, url } : item))} />
    <button type="button" disabled={!index} onClick={() => { const next = [...links]; [next[index - 1], next[index]] = [next[index], next[index - 1]]; onChange(next); }}>Move Up</button>{" "}
    <button type="button" onClick={() => onChange(links.filter(item => item.id !== link.id))}>Remove Link</button>
  </div>)}<label>New Link Label<input value={label} onChange={event => setLabel(event.target.value)} placeholder={title === "Social and support" ? "LinkedIn or Buy Me a Coffee" : "About"} /></label><label>New Destination<input value={url} onChange={event => setUrl(event.target.value)} placeholder="https://… or /page" /></label><button type="button" disabled={!label.trim() || !url.trim()} onClick={() => { onChange([...links, { id: templateId(), label: label.trim(), url: url.trim() }]); }}>Add Link</button></InspectorAccordionSection>;
}

export function TemplateInspector({ set, target, selectedBlock, writable, onChange, onBlockChange, onOpenMedia, onEditPart, users, tab: selectedTab, onTabChange }: {
  set: TemplateSet; target: PageTemplate | TemplatePart; selectedBlock: ContentBlock | null; writable: boolean;
  onChange: (set: TemplateSet) => void; onBlockChange: (block: ContentBlock) => void; onOpenMedia: (logo?: boolean) => void; onEditPart: (id: string) => void; users: string[];
  tab?: "template" | "styles" | "block"; onTabChange?: (tab: "template" | "styles" | "block") => void;
}) {
  const [localTab, setLocalTab] = useState<"template" | "styles" | "block">("template");
  const tab = selectedTab ?? localTab;
  function selectTab(nextTab: typeof tab) { setLocalTab(nextTab); onTabChange?.(nextTab); }
  const element = selectedBlock?.type === "group" ? selectedBlock.data?.templateElement : undefined;
  const partId = selectedBlock?.type === "group" ? selectedBlock.data?.templatePart : undefined;
  const templateTarget = target.kind === "page" || target.kind === "post" ? target : undefined;
  const defaults = templateTarget?.defaults ?? set.defaults ?? {};
  const changeDefaults = (next: NonNullable<TemplateSet["defaults"]>) => onChange(templateTarget ? { ...set, templates: set.templates.map(template => template.id === templateTarget.id ? { ...template, defaults: next } : template) } : { ...set, defaults: next });
  const changePalette = (key: keyof SiteStyles["palette"], colour: string) => onChange({ ...set, styles: { ...set.styles, palette: { ...set.styles.palette, [key]: colour } } });
  const changeBodyTypography = (patch: Partial<SiteStyles["typography"]["body"]>) => onChange({ ...set, styles: { ...set.styles, typography: { ...set.styles.typography, body: { ...set.styles.typography.body, ...patch } } } });
  const desktopBodySize = set.styles.typography.body.size.desktop;
  const bodySizeInPixels = Math.round(desktopBodySize.value * (desktopBodySize.unit === "px" ? 1 : 16));
  const changeLayout = (key: keyof SiteStyles["layout"], value: number) => onChange({ ...set, styles: { ...set.styles, layout: { ...set.styles.layout, [key]: value } } });
  return <aside className="studio-inspector template-inspector">
    <div className="pane-tabs inspector-tabs" role="tablist" aria-label="Template settings">{(["template", "block", "styles"] as const).map(item => <button type="button" key={item} role="tab" aria-selected={tab === item} className={tab === item ? "is-active" : ""} onClick={() => selectTab(item)}><span className="pane-tab-label">{item === "template" ? "Template" : item === "block" ? "Block" : "Styles"}</span></button>)}</div>
    <div className="inspector-scroll"><InspectorContentDisabledProvider disabled={!writable}>
      {tab === "block" ? selectedBlock ? element ? <InspectorAccordionSection contentDisabled={!writable} title={templateElementLabel(String(element))}><p>Content is supplied by the preview document or site identity.</p><label>Alignment<select value={String(selectedBlock.type === "group" ? selectedBlock.data?.align ?? "left" : "left")} onChange={event => onBlockChange({ ...selectedBlock, data: { ...(selectedBlock.type === "group" ? selectedBlock.data : {}), align: event.target.value } } as ContentBlock)}><option value="left">Left</option><option value="centre">Centre</option><option value="right">Right</option></select></label></InspectorAccordionSection> : partId ? <InspectorAccordionSection contentDisabled={!writable} title="Shared part"><label>Part<select value={String(partId)} onChange={event => onBlockChange({ ...selectedBlock, data: { templatePart: event.target.value } } as ContentBlock)}>{set.parts.map(part => <option value={part.id} key={part.id}>{part.name}</option>)}</select></label><button type="button" onClick={() => onEditPart(String(partId))}>Edit {set.parts.find(part => part.id === partId)?.name}</button></InspectorAccordionSection> : <BlockInspector block={selectedBlock} onChange={onBlockChange} onOpenFiles={() => onOpenMedia()} canOpenFiles /> : <p>Select a block in the canvas or List View.</p> : tab === "styles" ? <>
        <InspectorAccordionSection contentDisabled={!writable} title="Semantic colours"><p>Applies to every template in {set.name}. Explicit block styles take precedence.</p>
          {([ ["surface", "Surface"], ["surfaceRaised", "Raised surface"], ["surfaceSubtle", "Subtle surface"], ["textPrimary", "Primary text"], ["textSecondary", "Secondary text"], ["border", "Border"], ["accent", "Accent"], ["onAccent", "Text on accent"], ["success", "Success"], ["information", "Information"], ["alert", "Alert"], ["warning", "Warning"], ["rating", "Rating"] ] as [keyof SiteStyles["palette"], string][]).map(([key, label]) => <label key={key}>{label}<input type="color" value={set.styles.palette[key]} onChange={event => changePalette(key, event.target.value)} /></label>)}
        </InspectorAccordionSection>
        <InspectorAccordionSection contentDisabled={!writable} title="Body typography">
          <label>Typeface<select value={set.styles.typography.body.family} onChange={event => changeBodyTypography({ family: event.target.value as SiteStyles["typography"]["body"]["family"] })}><option value="inter">Inter</option><option value="system-sans">System Sans</option><option value="georgia">Georgia</option></select></label>
          <label>Body text size (px)<input type="number" min={8} max={96} step={1} value={bodySizeInPixels} onChange={event => { const value = Number(event.target.value); if (Number.isFinite(value) && value >= 8 && value <= 96) changeBodyTypography({ size: { ...set.styles.typography.body.size, desktop: { value, unit: "px" } } }); }} /></label>
          <label>Weight<select value={set.styles.typography.body.weight} onChange={event => changeBodyTypography({ weight: Number(event.target.value) })}>{Array.from({ length: 9 }, (_, index) => (index + 1) * 100).map(weight => <option value={weight} key={weight}>{weight}</option>)}</select></label>
          <label>Style<select value={set.styles.typography.body.style} onChange={event => changeBodyTypography({ style: event.target.value as "normal" | "italic" })}><option value="normal">Normal</option><option value="italic">Italic</option></select></label>
          <label>Text transform<select value={set.styles.typography.body.transform} onChange={event => changeBodyTypography({ transform: event.target.value as SiteStyles["typography"]["body"]["transform"] })}><option value="none">None</option><option value="uppercase">Uppercase</option><option value="lowercase">Lowercase</option><option value="capitalize">Capitalize</option></select></label>
          {([ ["lineHeight", "Line height", 0.8, 3], ["letterSpacing", "Letter spacing", -5, 20] ] as const).map(([key, label, min, max]) => <label key={key}>{label}<input type="number" min={min} max={max} step={0.05} value={set.styles.typography.body[key].desktop.value} onChange={event => { const value = Number(event.target.value); if (Number.isFinite(value) && value >= min && value <= max) changeBodyTypography({ [key]: { ...set.styles.typography.body[key], desktop: { ...set.styles.typography.body[key].desktop, value } } }); }} /></label>)}
        </InspectorAccordionSection>
        <InspectorAccordionSection contentDisabled={!writable} title="Shared layout">
          {([["spacing", "Spacing", 0, 120], ["contentWidth", "Content width", 320, 1800], ["radius", "Corner radius", 0, 80], ["borderWidth", "Border width", 0, 12]] as const).map(([key, label, min, max]) => <label key={key}>{label} (px)<input type="number" min={min} max={max} value={set.styles.layout[key]} onChange={event => { const value = Number(event.target.value); if (Number.isFinite(value) && value >= min && value <= max) changeLayout(key, value); }} /></label>)}
        </InspectorAccordionSection>
      </> : <>
        <InspectorAccordionSection contentDisabled={!writable} title={target.name}><p>{target.kind === "header" || target.kind === "footer" ? `Used by: ${users.join(", ") || "No templates yet"}.` : `Reusable ${target.kind} layout. Content is optional while exploring; add at most one Content element.`}</p></InspectorAccordionSection>
        <InspectorAccordionSection contentDisabled={!writable} title="Template defaults"><p>Documents inherit these values until they explicitly override them.</p>{templateTarget ? <><label className="checkbox-setting"><input type="checkbox" checked={Boolean(templateTarget.isDefault)} onChange={event => onChange({ ...set, templates: set.templates.map(template => template.kind === templateTarget.kind ? { ...template, isDefault: template.id === templateTarget.id ? event.target.checked : false } : template) })} /><span>Use as default {templateTarget.kind} template</span></label><TemplateTextSetting label="Author" value={defaults.author ?? ""} placeholder="No default author" onCommit={author => changeDefaults({ ...defaults, author: author || undefined })} /><TemplateTextSetting label="Category" value={defaults.category ?? ""} placeholder="No default category" onCommit={value => changeDefaults({ ...defaults, category: value || undefined })} /><TemplateTextSetting label="Tags" value={(defaults.tags ?? []).join(", ")} placeholder="No default tags" onCommit={value => changeDefaults({ ...defaults, tags: value.split(",").map(tag => tag.trim()).filter(Boolean) })} /><TemplateTextSetting label="Parent page" value={defaults.parentPageId ?? ""} placeholder="No default parent" onCommit={value => changeDefaults({ ...defaults, parentPageId: value || undefined })} /><h4>Field display defaults</h4>{(["title", "subtitle", "coverImage", "author", "publicationDate", "readingTime"] as const).map(field => <label key={field}>{field === "coverImage" ? "Cover image" : field === "publicationDate" ? "Publication date" : field === "readingTime" ? "Reading time" : field.charAt(0).toUpperCase() + field.slice(1)}<select value={templateTarget.displayDefaults?.[field] ?? "show"} onChange={event => onChange({ ...set, templates: set.templates.map(template => template.id === templateTarget.id ? { ...template, displayDefaults: { ...template.displayDefaults, [field]: event.target.value as "show" | "hide" } } : template) })}><option value="show">Show</option><option value="hide">Hide</option></select></label>)}</> : <p className="setting-note">Shared parts do not own document defaults.</p>}</InspectorAccordionSection>
        <InspectorAccordionSection contentDisabled={!writable} title="Site identity"><TemplateTextSetting label="Site Name" value={set.identity.name} onCommit={name => onChange({ ...set, identity: { ...set.identity, name } })} />
        <TemplateTextSetting label="Home Address" value={set.identity.homeUrl} onCommit={homeUrl => onChange({ ...set, identity: { ...set.identity, homeUrl } })} />
        <TemplateTextSetting label="Copyright" value={set.identity.copyright} onCommit={copyright => onChange({ ...set, identity: { ...set.identity, copyright } })} />
        <button type="button" onClick={() => onOpenMedia(true)}>Choose Logo</button>{set.identity.logo ? <><TemplateTextSetting label="Logo Alternative Text" value={set.identity.logo.alt} onCommit={alt => onChange({ ...set, identity: { ...set.identity, logo: { ...set.identity.logo!, alt } } })} /><button type="button" onClick={() => onChange({ ...set, identity: { ...set.identity, logo: undefined } })}>Remove Logo</button></> : null}
        </InspectorAccordionSection>
        <LinkSettings title="Navigation" links={set.navigation} onChange={navigation => onChange({ ...set, navigation })} disabled={!writable} />
        <LinkSettings title="Social and support" links={set.socialLinks} onChange={socialLinks => onChange({ ...set, socialLinks })} disabled={!writable} />
      </>}
    </InspectorContentDisabledProvider></div>
  </aside>;
}
